### ISSUE TITLE
macOS has issues calling GitHub API

### ISSUE THREAD

**Issue by lcombs15** [DiscordHooks/github-actions-discord-webhook#10]
The pull request API call is hit or miss on macOS. Windows and Linux have no issues.

Screenshot:
![image](https://user-images.githubusercontent.com/3866197/66257456-83c6c380-e767-11e9-8a0d-cdba2bc9026d.png)

This file needs some kind of change:
https://github.com/DiscordHooks/github-actions-discord-webhook/blob/fe1f00d9ccd1e0e4da188b3c3c059d518069481e/get_pull_request_title.rb#L13

Maybe it could be wrapped in a loop to try 10 times or something? It would also be nice if this file printed lots of details whenever it doesn't have HTTP OK.

**Comment by iamtraction** [comment]
Any reason why it's a hit or a miss?

**Comment by lcombs15** [comment]
> Any reason why it's a hit or a miss?

Truthfully, I'm not sure.

In one of my repos that uses this, I have a matrix.os so jobs run on Windows, Linux, and MacOS.

On the same PR, Windows and Linux run fine, but Mac throws this error.

Either it's hit or miss OR it's some strange special character issue. None-the-less, once this is merged, I'll have more info about it the next time it happens. This prints more info, IE response code, rather than `Had an issue........`
