### ISSUE TITLE
Job status check is case sensitive

### ISSUE THREAD

**Issue by varGeneric** [DiscordHooks/github-actions-discord-webhook#13]
The example configuration does not work for me as my job returns a fully lower-case "success"/"failure"/"cancelled". It appears that the script checks for "Success" with a capital S which causes my job to be reported as status unknown. 

Proposed fix is to just [convert the input string to lower case](https://stackoverflow.com/questions/2264428/how-to-convert-a-string-to-lower-case-in-bash) and check against lower case versions of the current strings.

**Comment by iamtraction** [comment]
Would you like to open a PR?

**Comment by varGeneric** [comment]
Opened #14.
