### ISSUE TITLE
GitHub Actions Support

### ISSUE THREAD

**Issue by Stanzilla** [DiscordHooks/github-actions-discord-webhook#2]
Wrong repo, I know, but any plans for a GitHub Actions Discord Hook?

**Comment by Stanzilla** [comment]
Oh hey, a friend of mine started on this https://gist.github.com/nebularg/d76b43032331bff1b8bb60767e699a32

**Comment by iamtraction** [comment]
PRs are welcome! 👌

**Comment by lcombs15** [comment]
I had opened PR #1 by accident--I forget what I was trying to do at the time.... It's ***very*** rough and I haven't even had time to test it. I'll keep working on it and I'll open an actual PR if I get it to a decent state. 💯

**Comment by Stanzilla** [comment]
Currently living here https://github.com/nebularg/actions-discord-webhook
